<a href="https://colab.research.google.com/github/Ftoker/exametry-ai-sprint/blob/main/Copy_of_Untitled21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q transformers

In [ ]:
from transformers import pipeline

In [ ]:
classifier = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

In [ ]:
text = " I am so happy"

In [ ]:
classifier (text)

[{'label': 'POSITIVE', 'score': 0.9995287656784058}]

In [ ]:
import pandas as pd
outputs = classifier (text)
pd.DataFrame (outputs)

      label     score
0  POSITIVE  0.999881

In [ ]:
classifier = pipeline("zero-shot-classification")

No model was supplied, defaulted to facebook/bart-large-mnli and revision d7645e1.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
text = "This is tutorial about trade"

In [ ]:
labels = ["tech","education","business"]

In [ ]:
outputs = classifier (text, labels)
pd.DataFrame (outputs)

                       sequence     labels    scores
0  This is tutorial about trade   business  0.952289
1  This is tutorial about trade       tech  0.028273
2  This is tutorial about trade  education  0.019437

In [ ]:
generator = pipeline ("text-generation")

No model was supplied, defaulted to openai-community/gpt2 and revision 607a30d.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: openai-community/gpt2
Key                  | Status     |  |
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
prompt="this tutorial will walk you through how to"

In [ ]:
outputs = generator(prompt)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [ ]:
print (outputs[0]["generated_text"])

this tutorial will walk you through how to set up a simple and easy to use build system for your Android project.

This article is going to show you how to set up the Android Studio to build a simple app for your project. If you are new to Android Studio, this is the tutorial that will cover building applications using the Android Studio.

As you probably know, the Android Studio is a fairly simple project. It basically consists of the following steps:

1. Start Android Studio by going to File → Properties → Build → Build.

You will see a list of the files you have to build (this list is not a list of all your files, it is a list of all your files that you have already built). When you are done, go back into the Android Studio Editor and choose the Android Studio Build button. You will then have to select the Android Studio Project.

2. In the Android Studio Build menu, select Build and choose to build from the drop down menu. This will bring up the Android Studio Build button.

3. After clicking the Build button, you will see a list of files you have to build (this list is a list of all your files that you have already built).

4. When you select the button, you